version: '3'

services:
  missingpets.site:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"
  missingpets.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"
networks:
  default:
    external:
      name: nat

